export const BASE_URL = process.env.BASE_URL;
export const SIGN_IN = "API/Account/authenticate";
export const GET_MY_TASKS = "API/Task/UserTasksAssignedToMe";
export const GET_LEADS = "API/CRM/Leads";
export const GET_COMPONY_MEM = "API/CompanyMembers";
export const GET_TASK_STATUS_FOR_PARTIAL = "API/Task/UserTaskStatusMaster"; //get which gives percentage
export const POST_UPDATE_TASK = "API/Task/UpdateTaskStatus"; //post// for accepting the and submitting form with completion %
export const POST_MY_TEAM = "API/CRM/MyTeam";
export const DELETE_TASK = "API/Task/DeleteTask"; // delete task
export const CALL_AT_START = "API/WebAppSetting";
export const ASSIGNTASK="API/Task/AssignTask";
